/**
 * Mule FWS Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */

package org.mule.module.fws;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertSame;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.eq;
import static org.mockito.Matchers.isNull;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;
import static org.mule.module.fws.api.Arrays.asArray;

import org.mule.module.fws.api.AxisFWSClient;
import org.mule.module.fws.api.FwsException;
import org.mule.module.fws.api.ItemCondition;
import org.mule.module.fws.api.LabelPreference;
import org.mule.module.fws.api.PortProvider;
import org.mule.module.fws.api.ShipmentStatus;
import org.mule.module.fws.api.internal.Address;
import org.mule.module.fws.api.internal.AmazonFBAInventoryPortType;
import org.mule.module.fws.api.internal.AmazonFBAOutboundPortType;
import org.mule.module.fws.api.internal.AmazonFWSInboundPortType;
import org.mule.module.fws.api.internal.CreateFulfillmentOrderItem;
import org.mule.module.fws.api.internal.Currency;
import org.mule.module.fws.api.internal.FulfillmentItem;
import org.mule.module.fws.api.internal.FulfillmentOrder;
import org.mule.module.fws.api.internal.FulfillmentPreview;
import org.mule.module.fws.api.internal.GetFulfillmentIdentifierForMSKUResult;
import org.mule.module.fws.api.internal.GetFulfillmentIdentifierResult;
import org.mule.module.fws.api.internal.GetFulfillmentItemByFNSKUResult;
import org.mule.module.fws.api.internal.GetFulfillmentItemByMSKUResult;
import org.mule.module.fws.api.internal.GetFulfillmentOrderResult;
import org.mule.module.fws.api.internal.GetFulfillmentPreviewItem;
import org.mule.module.fws.api.internal.GetFulfillmentPreviewResult;
import org.mule.module.fws.api.internal.GetInboundShipmentDataResult;
import org.mule.module.fws.api.internal.GetServiceStatusResult;
import org.mule.module.fws.api.internal.InboundShipmentData;
import org.mule.module.fws.api.internal.InboundShipmentItem;
import org.mule.module.fws.api.internal.MerchantItem;
import org.mule.module.fws.api.internal.MerchantSKUSupply;
import org.mule.module.fws.api.internal.ShipmentPreview;
import org.mule.module.fws.api.internal.holders.GetFulfillmentIdentifierForMSKUResultHolder;
import org.mule.module.fws.api.internal.holders.GetFulfillmentIdentifierResultHolder;
import org.mule.module.fws.api.internal.holders.GetFulfillmentItemByFNSKUResultHolder;
import org.mule.module.fws.api.internal.holders.GetFulfillmentItemByMSKUResultHolder;
import org.mule.module.fws.api.internal.holders.GetFulfillmentOrderResultHolder;
import org.mule.module.fws.api.internal.holders.GetFulfillmentPreviewResultHolder;
import org.mule.module.fws.api.internal.holders.GetInboundShipmentDataResultHolder;
import org.mule.module.fws.api.internal.holders.GetServiceStatusResultHolder;
import org.mule.module.fws.api.internal.holders.ResponseMetadataHolder;

import java.rmi.RemoteException;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.mockito.invocation.InvocationOnMock;
import org.mockito.stubbing.Answer;

public class FWSUnitTest
{
    private static final String STATUS_MESSAGE = "OK";
    private static final String ASIN = "ASIN";
    private static final String SHIP_ID = "SHIP_ID";
    private static final String NSKU = "NSKU";
    private static final String MSKU = "MSKU";
    private FWSCloudConnector connector;
    private static final String ORDER_ID = "ORDER_ID";
    private static final String ORDER_ITEM_ID = "ORDER_ITEM_ID";
    private AmazonFBAInventoryPortType inventory = mock(AmazonFBAInventoryPortType.class);
    private AmazonFBAOutboundPortType out = mock(AmazonFBAOutboundPortType.class);
    private AmazonFWSInboundPortType in = mock(AmazonFWSInboundPortType.class);

    @Before
    @SuppressWarnings("unchecked")
    public void setup() throws RemoteException
    {
        connector = new FWSCloudConnector();
        PortProvider<AmazonFWSInboundPortType> inboundProvider = mock(PortProvider.class);
        PortProvider<AmazonFBAOutboundPortType> outboundProvider = mock(PortProvider.class);
        PortProvider<AmazonFBAInventoryPortType> inventoryProvider = mock(PortProvider.class);

        connector.setClient(new AxisFWSClient(inboundProvider, outboundProvider, inventoryProvider));

        when(inboundProvider.getPort(anyString())).thenReturn(in);
        when(outboundProvider.getPort(anyString())).thenReturn(out);
        when(inventoryProvider.getPort(anyString())).thenReturn(inventory);
    }

    @After
    public void verifyNoMoreInteraction()
    {
        verifyNoMoreInteractions(in, out, inventory);
    }

    @Test
    public void cancelFulfillmentOrder() throws RemoteException
    {
        connector.cancelFulfillmentOrder(ORDER_ID);
        verify(out).cancelFulfillmentOrder(eq(ORDER_ID));
    }

    @Ignore
    @Test
    public void createFulfillmentOrder() throws RemoteException
    {
        connector.createFulfillmentOrder(ORDER_ID, null, new Address(), null, null, "QUICK", "An order",
            new GregorianCalendar(2011, Calendar.JUNE, 28, 15, 0, 0).getTime(), null,
            Arrays.asList(new CreateFulfillmentOrderItem(MSKU, "1", 1, "", "An item", "", NSKU,
                new Currency())));
        verify(out).createFulfillmentOrder(eq(ORDER_ID), eq(ORDER_ID), eq("2011-06-28T15:00Z"),
            eq("An order"), null, eq(new Address()), eq("QUICK"), null, null, null);
    }

    @Test
    public void deleteInboundShipmentItems() throws RemoteException
    {
        connector.deleteInboundShipmentItems(MSKU, SHIP_ID);
        verify(in).deleteInboundShipmentItems(eq(SHIP_ID), eq(new String[]{MSKU}));
    }

    @Test
    public void getFulfillmentIdentifier() throws RemoteException
    {
        doAnswer(new UpdateHolderAnswer<GetFulfillmentIdentifierResultHolder>(1)
        {
            @Override
            void updateHolder(GetFulfillmentIdentifierResultHolder h)
            {
                h.value = new GetFulfillmentIdentifierResult(asArray(new FulfillmentItem()));
            }
        }).when(in).getFulfillmentIdentifier( //
            eq(asArray(new MerchantItem(ASIN,
                org.mule.module.fws.api.internal.ItemCondition.NewItem, MSKU))), //
            any(GetFulfillmentIdentifierResultHolder.class), //
            anyMetadata());
        connector.getFulfillmentIdentifier(ASIN, ItemCondition.NEW_ITEM, MSKU);
        reset(in);
    }
    
    @Test
    public void getFulfillmentIdentifierForMsku() throws RemoteException
    {
        getFulfillmentIdForMsku(asArray(new FulfillmentItem()));
    }

    @Ignore
    @Test(expected = FwsException.class)
    public void getFulfillmentIdentifierForMskuInvallidId() throws RemoteException
    {
        getFulfillmentIdForMsku(new FulfillmentItem[0]);
    }

    private void getFulfillmentIdForMsku(final FulfillmentItem[] fulfillmentItem) throws RemoteException
    {
        doAnswer(new UpdateHolderAnswer<GetFulfillmentIdentifierForMSKUResultHolder>(1)
        {
            @Override
            void updateHolder(GetFulfillmentIdentifierForMSKUResultHolder h)
            {
                h.value = new GetFulfillmentIdentifierForMSKUResult(fulfillmentItem);
            }
        }).when(in).getFulfillmentIdentifierForMSKU(eq(asArray(MSKU)),
            any(GetFulfillmentIdentifierForMSKUResultHolder.class), anyMetadata());
        connector.getFulfillmentIdentifierForMsku(MSKU);
        reset(in);
    }

    @Test
    public void getFulfillmentItemByFnsku() throws RemoteException
    {
        getFulfillmentByFnsku(asArray(new FulfillmentItem()));
    }
    
    @Ignore
    @Test(expected = FwsException.class)
    public void getFulfillmentItemByFnskuInvallidId() throws RemoteException
    {
        getFulfillmentByFnsku(new FulfillmentItem[0]);
    }

    private void getFulfillmentByFnsku(final FulfillmentItem[] result) throws RemoteException
    {
        doAnswer(new UpdateHolderAnswer<GetFulfillmentItemByFNSKUResultHolder>(1)
        {
            @Override
            void updateHolder(GetFulfillmentItemByFNSKUResultHolder h)
            {
                h.value = new GetFulfillmentItemByFNSKUResult(result);
            }
        }).when(in).getFulfillmentItemByFNSKU(eq(asArray(NSKU)),
            any(GetFulfillmentItemByFNSKUResultHolder.class), anyMetadata());
        connector.getFulfillmentItemByFnsku(NSKU);
        reset(in);
    }

    @Test
    public void getFulfillmentItemByMsku() throws RemoteException
    {
        doAnswer(new UpdateHolderAnswer<GetFulfillmentItemByMSKUResultHolder>(1)
        {
            @Override
            void updateHolder(GetFulfillmentItemByMSKUResultHolder h)
            {
                final FulfillmentItem[] returnedItems = asArray(new FulfillmentItem());
                h.value = new GetFulfillmentItemByMSKUResult(returnedItems);
            }
        }).when(in).getFulfillmentItemByMSKU(eq(new String[]{MSKU}),
            any(GetFulfillmentItemByMSKUResultHolder.class), anyMetadata());
        connector.getFulfillmentItemByMsku(MSKU);
        reset(in);
    }

    @Test
    public void getFulfillmentOrder() throws RemoteException
    {
        final GetFulfillmentOrderResult result = new GetFulfillmentOrderResult();
        doAnswer(new UpdateHolderAnswer<GetFulfillmentOrderResultHolder>(1)
        {
            @Override
            void updateHolder(GetFulfillmentOrderResultHolder h)
            {
                h.value = result;
            }
        }).when(out).getFulfillmentOrder(eq(ORDER_ID), any(GetFulfillmentOrderResultHolder.class),
            anyMetadata());
        assertSame(result, connector.getFulfillmentOrder(ORDER_ID));
        reset(out);
    }
    
    @Test
    public void getFulfillmentPreviewWithCategories() throws RemoteException
    {
        final Address address = new Address();
        doAnswer(updatePreview()).when(out).getFulfillmentPreview(eq(address),
            eq(asArray(new GetFulfillmentPreviewItem(MSKU, 10, ORDER_ITEM_ID))), (String[]) isNull(),
            any(GetFulfillmentPreviewResultHolder.class), anyMetadata());
        connector.getFulfillmentPreview(address, MSKU, null, 10, ORDER_ITEM_ID);
        reset(out);
    }

    @Test
    public void getFulfillmentPreviewWithoutCategories() throws RemoteException
    {
        final Address address = new Address();
        doAnswer(updatePreview()).when(out).getFulfillmentPreview(eq(address),
            eq(asArray(new GetFulfillmentPreviewItem(MSKU, 10, ORDER_ITEM_ID))), eq(asArray("CAT-1")),
            any(GetFulfillmentPreviewResultHolder.class), anyMetadata());
        connector.getFulfillmentPreview(new Address(), MSKU, "CAT-1", 10, ORDER_ITEM_ID);
        reset(out);
    }

    @Test
    public void getInboundServiceStatus() throws RemoteException
    {
        doAnswer(updateStatus()).when(in).getServiceStatus(any(GetServiceStatusResultHolder.class),
            anyMetadata());
        assertEquals(STATUS_MESSAGE, connector.getInboundServiceStatus());
        reset(in);
    }

    @Test
    public void getInventoryServiceStatus() throws RemoteException
    {
        doAnswer(updateStatus()).when(inventory).getServiceStatus(any(GetServiceStatusResultHolder.class),
            anyMetadata());
        assertEquals(STATUS_MESSAGE, connector.getInventoryServiceStatus());
        reset(inventory);
    }

    @Test
    public void getOutboundServiceStatus() throws RemoteException
    {
        doAnswer(updateStatus()).when(out).getServiceStatus(any(GetServiceStatusResultHolder.class),
            anyMetadata());
        assertEquals(STATUS_MESSAGE, connector.getOutboundServiceStatus());
        reset(out);
    }

    @Test
    public void getInboundShipment() throws RemoteException
    {
        final InboundShipmentData shipmentData = new InboundShipmentData();
        doAnswer(new UpdateHolderAnswer<GetInboundShipmentDataResultHolder>(1)
        {
            @Override
            void updateHolder(GetInboundShipmentDataResultHolder h)
            {
                h.value = new GetInboundShipmentDataResult(shipmentData);
            }
        }).when(in).getInboundShipmentData(eq(SHIP_ID), any(GetInboundShipmentDataResultHolder.class),
            anyMetadata());
        assertSame(shipmentData, connector.getInboundShipment(SHIP_ID));
        reset(in);
    }

    @Ignore
    @Test
    public void getInboundShipmentPreview()
    {
        connector.getInboundShipmentPreview(MSKU, 10, new Address(), LabelPreference.MERCHANT_LABEL);
    }

    @Ignore
    @Test
    public void getInventorySupplyWithoutGroup()
    {
        connector.getInventorySupply(MSKU, null);
    }
    
    @Ignore
    @Test
    public void getInventorySupplyWithGroup()
    {
        connector.getInventorySupply(MSKU, "a group");
    }

    @Test
    public void listFulfillmentItems()
    {
        connector.listFulfillmentItems(false);
    }

    @Test
    public void listFulfillmentOrdersWithoutDate()
    {
        connector.listFulfillmentOrders(null);
    }
    
    @Test
    public void listFulfillmentOrdersWithDate()
    {
        connector.listFulfillmentOrders(new Date());
    }

    @Test
    public void listInboundShipmentItems()
    {
        connector.listInboundShipmentItems(SHIP_ID);
    }

    @Test
    public void listInboundShipmentsWithoutBeforeDate()
    {
        connector.listInboundShipments(ShipmentStatus.ERROR, new Date(), null);
    }
    
    @Test
    public void listInboundShipmentsWithAfterDate()
    {
        connector.listInboundShipments(ShipmentStatus.ERROR, null, new Date());
    }

    @Test
    public void listUpdatedInventorySupplyWithoutGroup()
    {
        connector.listUpdatedInventorySupply(new Date(), null);
    }
    
    @Test
    public void listUpdatedInventorySupplyWithGroup()
    {
        connector.listUpdatedInventorySupply(new Date(), "");
    }

    @Test
    @Ignore
    public void putInboundShipment()
    {
        Address shipFromAddress = new Address();
        connector.putInboundShipment(SHIP_ID, "A shipment", "a center", shipFromAddress,
            LabelPreference.AMAZON_LABEL_ONLY);
    }

    @Test
    @Ignore
    public void putInboundShipmentItems()
    {
//        Address shipFromAddress = new Address();
//        connector.putInboundShipmentItems(SHIP_ID, "A shipment", "a center", shipFromAddress,
//            LabelPreference.AMAZON_LABEL_ONLY);
    }

    @Test
    public void setInboundShipmentStatus() throws RemoteException
    {
        connector.setInboundShipmentStatus(SHIP_ID, ShipmentStatus.DELIVERED);
        verify(in).setInboundShipmentStatus(SHIP_ID,
            org.mule.module.fws.api.internal.ShipmentStatus.Delivered);
    }

    abstract class UpdateHolderAnswer<HolderType> implements Answer<Void>
    {
        private final int holderArgPosition;

        UpdateHolderAnswer(int holderArgPosition)
        {
            this.holderArgPosition = holderArgPosition;
        }

        @SuppressWarnings("unchecked")
        public final Void answer(InvocationOnMock invocation) throws Throwable
        {
            updateHolder(((HolderType) invocation.getArguments()[holderArgPosition]));
            return null;
        }

        abstract void updateHolder(HolderType h);
    }

    private Answer<Void> updateStatus()
    {
        return new UpdateHolderAnswer<GetServiceStatusResultHolder>(0)
        {
            @Override
            void updateHolder(GetServiceStatusResultHolder h)
            {
                h.value = new GetServiceStatusResult(STATUS_MESSAGE);
            }
        };
    }
    
    private UpdateHolderAnswer<GetFulfillmentPreviewResultHolder> updatePreview()
    {
        return new UpdateHolderAnswer<GetFulfillmentPreviewResultHolder>(3)
        {
            @Override
            void updateHolder(GetFulfillmentPreviewResultHolder h)
            {
                h.value = new GetFulfillmentPreviewResult(new FulfillmentPreview[0]);
            }
        };
    }
    
    private ResponseMetadataHolder anyMetadata()
    {
        return any(ResponseMetadataHolder.class);
    }


}
